In [3]:
import duckdb
import pandas as pd

In [4]:
sql_query = '''
select * from parking_violation_codes limit 10
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,code,definition,manhattan_96th_st_below,all_other_areas
0,1,FAILURE TO DISPLAY BUS PERMIT,515,515
1,2,NO OPERATOR NAM/ADD/PH DISPLAY,515,515
2,3,UNAUTHORIZED PASSENGER PICK-UP,515,515
3,4,BUS PARKING IN LOWER MANHATTAN,115,115
4,5,BUS LANE VIOLATION,250,250
5,6,OVERNIGHT TRACTOR TRAILER PKG,500,500
6,7,FAILURE TO STOP AT RED LIGHT,50,50
7,8,IDLING,115,115
8,9,OBSTRUCTING TRAFFIC/INTERSECT,115,115
9,10,NO STOPPING-DAY/TIME LIMITS,115,115

In [5]:
sql_query = '''
show tables
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                              name
0   bronze_parking_violation_codes
1        bronze_parking_violations
2                      first_model
3              gold_ticket_metrics
4            gold_vehicles_metrics
5          parking_violation_codes
6          parking_violations_2023
7                        ref_model
8   silver_parking_violation_codes
9        silver_parking_violations
10        silver_violation_tickets
11       silver_violation_vehicles